### ISSUE TITLE
Segmetation fault during input

### ISSUE THREAD

**Issue by eternal-sorrow** [tadeokondrak/anthywl#25]
I sometimes get segfault during input of japanese text. Stacktrace looks like this:
```
#0  0x0000565453aac702 in anthywl_buffer_convert_romaji (buffer=buffer@entry=0x565455a4efa8) at ../anthywl-9999/src/buffer.c:447
#1  0x0000565453aaa759 in anthywl_seat_handle_key (seat=seat@entry=0x565455a4ed00, keycode=keycode@entry=38) at ../anthywl-9999/src/anthywl.c:579
#2  0x0000565453aaa882 in zwp_input_method_keyboard_grab_v2_key (data=0x565455a4ed00, zwp_input_method_keyboard_grab_v2=<optimized out>, serial=<optimized out>, time=5393884, key=30, state=1)
    at ../anthywl-9999/src/anthywl.c:749
#3  0x00007f9e6eab3f7a in ?? () from /usr/lib64/libffi.so.8
#4  0x00007f9e6eab036d in ?? () from /usr/lib64/libffi.so.8
#5  0x00007f9e6eab364d in ffi_call () from /usr/lib64/libffi.so.8
#6  0x00007f9e6f063ca6 in wl_closure_invoke (closure=closure@entry=0x565455a89100, flags=flags@entry=1, target=<optimized out>, target@entry=0x565455a97d50, opcode=opcode@entry=1, data=<optimized out>)
    at ../wayland-1.22.0/src/connection.c:1025
#7  0x00007f9e6f060e27 in dispatch_event (display=display@entry=0x565455a49cc0, queue=queue@entry=0x565455a49db0) at ../wayland-1.22.0/src/wayland-client.c:1631
#8  0x00007f9e6f0623f5 in dispatch_queue (queue=0x565455a49db0, display=0x565455a49cc0) at ../wayland-1.22.0/src/wayland-client.c:1777
#9  wl_display_dispatch_queue_pending (display=0x565455a49cc0, queue=0x565455a49db0) at ../wayland-1.22.0/src/wayland-client.c:2019
#10 0x00007f9e6f06240f in wl_display_dispatch_pending (display=<optimized out>) at ../wayland-1.22.0/src/wayland-client.c:2082
#11 0x0000565453aab5a3 in anthywl_state_run (state=state@entry=0x7ffc5910ae80) at ../anthywl-9999/src/anthywl.c:1276
#12 0x0000565453aab790 in main () at ../anthywl-9999/src/anthywl.c:1347
```

**Comment by eternal-sorrow** [comment]
That was quick, thanks.
